version: '3.8'

services:
  api:
    container_name: nestjs-google-auth20
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: npm run start:dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - oauth20
  database:
    image: postgres
    container_name: nestjs-google-auth20-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oauth20
    ports:
      - "5432:5432"
    volumes:
      - /:/data/postgres
    networks:
      - oauth20

networks:
  oauth20:
    driver: bridge
